-- Create wingpost_locations table
CREATE TABLE IF NOT EXISTS wingpost_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  badge TEXT,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  rating DECIMAL(2,1) DEFAULT 4.9,
  reviews INTEGER DEFAULT 0,
  distance TEXT,
  thumbnail TEXT,
  image TEXT,
  phone TEXT NOT NULL,
  hours TEXT NOT NULL,
  maps_url TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Enable RLS
ALTER TABLE wingpost_locations ENABLE ROW LEVEL SECURITY;

-- Create policy for service role to do everything
CREATE POLICY "Service role can do everything" ON wingpost_locations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Create policy for authenticated users to read
CREATE POLICY "Authenticated users can view" ON wingpost_locations
  FOR SELECT
  TO authenticated
  USING (true);

-- Create index on is_active for faster queries
CREATE INDEX IF NOT EXISTS idx_wingpost_locations_is_active ON wingpost_locations(is_active);

-- Create index on name for search
CREATE INDEX IF NOT EXISTS idx_wingpost_locations_name ON wingpost_locations(name);

-- Insert initial data from the static locations
INSERT INTO wingpost_locations (
  name, badge, address, city, rating, reviews, distance,
  thumbnail, image, phone, hours, maps_url
) VALUES
  (
    'Microsoft Nigeria',
    'Popular',
    'Walter Carrington Crescent',
    'Victoria Island, Lagos',
    4.9,
    1245,
    '0.5 km',
    '/wingpost-location-1.jpg',
    '/wingpost-location-1.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Microsoft+Nigeria+Walter+Carrington+Crescent+Victoria+Island+Lagos'
  ),
  (
    'J Signature Hotel',
    NULL,
    '146 Omerelu Isiokpo Road',
    'Port Harcourt',
    4.9,
    1245,
    '0.8 km',
    '/wingpost-location-2.jpg',
    '/wingpost-location-2.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Js+Nightcare+Hotel+146+Omerelu+Isiokpo+Road+Port+Harcourt'
  ),
  (
    'Alliance Hotel',
    NULL,
    'Ikwerre Road',
    'Port Harcourt',
    4.9,
    1245,
    '1.2 km',
    '/wingpost-location-3.jpg',
    '/wingpost-location-3.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Alliance+Hotel+Ikwerre+Road+Port+Harcourt'
  ),
  (
    'Erastus Hotels',
    NULL,
    'Ikwerre Road',
    'Port Harcourt',
    4.9,
    1245,
    '1.5 km',
    '/wingpost-location-4.jpg',
    '/wingpost-location-4.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Erastus+Hotels+Ikwerre+Road+Port+Harcourt'
  ),
  (
    'Serenity Lodge',
    NULL,
    'Elechi',
    'Diobu, Rivers State',
    4.9,
    1245,
    '2.0 km',
    '/wingpost-location-5.jpg',
    '/wingpost-location-5.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Serenity+Lodge+Elechi+Diobu+Rivers+State'
  ),
  (
    'Palm Valley Hotel',
    NULL,
    'Airport Road',
    'Port Harcourt',
    4.9,
    1245,
    '2.5 km',
    '/wingpost-location-6.jpg',
    '/wingpost-location-6.jpg',
    '08090191999',
    '8:00 AM - 10:00 PM Daily',
    'https://www.google.com/maps/search/?api=1&query=Palm+Valley+Hotel+Airport+Road+Port+Harcourt'
  )
ON CONFLICT DO NOTHING;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_wingpost_locations_updated_at
  BEFORE UPDATE ON wingpost_locations
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
